{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMtvtiw2ZyZGiWCD29/X3OX",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/muhammathjibreel25/Healthcare-Diagnostic-and-Treatment/blob/main/project.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "-lRCS4PTtDND"
      },
      "outputs": [],
      "source": [
        "#!/usr/bin/env python3\n",
        "import random\n",
        "import argparse\n",
        "import logging\n",
        "from datetime import datetime, timedelta\n",
        "from typing import List, Tuple, Dict\n",
        "\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib.dates import DateFormatter\n",
        "\n",
        "# Configure logging\n",
        "logging.basicConfig(\n",
        "    level=logging.INFO,\n",
        "    format=\"%(asctime)s %(levelname)s: %(message)s\",\n",
        "    datefmt=\"%Y-%m-%d %H:%M:%S\"\n",
        ")\n",
        "\n",
        "# Constants for mapping\n",
        "SYMPTOMS_TO_CONDITIONS: Dict[str, List[str]] = {\n",
        "    'fever': ['Flu', 'COVID-19'],\n",
        "    'cough': ['Bronchitis', 'COVID-19'],\n",
        "    'fatigue': ['Anemia', 'Flu'],\n",
        "}\n",
        "\n",
        "TREATMENTS: Dict[str, List[str]] = {\n",
        "    'Flu': ['Rest', 'Hydration', 'Paracetamol'],\n",
        "    'COVID-19': ['Isolation', 'Antiviral medication', 'Oxygen therapy'],\n",
        "    'Bronchitis': ['Cough syrup', 'Antibiotics', 'Steam inhalation'],\n",
        "    'Anemia': ['Iron supplements', 'Dietary adjustments'],\n",
        "}\n",
        "\n",
        "\n",
        "def diagnose(symptoms: List[str]) -> List[Tuple[str, int]]:\n",
        "    \"\"\"\n",
        "    Count possible conditions based on reported symptoms.\n",
        "\n",
        "    Args:\n",
        "        symptoms: List of symptom keywords.\n",
        "\n",
        "    Returns:\n",
        "        Sorted list of tuples (condition, score) descending by likelihood.\n",
        "    \"\"\"\n",
        "    scores: Dict[str, int] = {}\n",
        "    for symptom in symptoms:\n",
        "        for condition in SYMPTOMS_TO_CONDITIONS.get(symptom, []):\n",
        "            scores[condition] = scores.get(condition, 0) + 1\n",
        "\n",
        "    # Sort by score descending, then alphabetically\n",
        "    sorted_conditions = sorted(\n",
        "        scores.items(), key=lambda item: (-item[1], item[0])\n",
        "    )\n",
        "    return sorted_conditions\n",
        "\n",
        "\n",
        "def suggest_treatment(condition: str) -> List[str]:\n",
        "    \"\"\"\n",
        "    Return recommended treatment steps for the top condition.\n",
        "    \"\"\"\n",
        "    return TREATMENTS.get(condition, ['Consult a healthcare professional'])\n",
        "\n",
        "\n",
        "def generate_iot_data(minutes: int = 10) -> pd.DataFrame:\n",
        "    \"\"\"\n",
        "    Simulate IoT health vitals over a time window.\n",
        "\n",
        "    Args:\n",
        "        minutes: Number of minutes to simulate.\n",
        "\n",
        "    Returns:\n",
        "        DataFrame with Time, Temperature, Heart Rate, and Oxygen Level.\n",
        "    \"\"\"\n",
        "    base_time = datetime.now()\n",
        "    times = [base_time + timedelta(minutes=i) for i in range(minutes)]\n",
        "    data = {\n",
        "        'Time': times,\n",
        "        'Temperature (°C)': [round(random.uniform(36.5, 38.5), 2) for _ in range(minutes)],\n",
        "        'Heart Rate (bpm)': [random.randint(60, 100) for _ in range(minutes)],\n",
        "        'Oxygen Level (%)': [random.randint(92, 100) for _ in range(minutes)]\n",
        "    }\n",
        "    return pd.DataFrame(data)\n",
        "\n",
        "\n",
        "def plot_vitals(df: pd.DataFrame) -> None:\n",
        "    \"\"\"\n",
        "    Plot simulated IoT health metrics.\n",
        "    \"\"\"\n",
        "    fig, ax = plt.subplots(figsize=(12, 6))\n",
        "    ax.plot(df['Time'], df['Temperature (°C)'], label='Temperature (°C)', marker='o')\n",
        "    ax.plot(df['Time'], df['Heart Rate (bpm)'], label='Heart Rate (bpm)', marker='x')\n",
        "    ax.plot(df['Time'], df['Oxygen Level (%)'], label='Oxygen Level (%)', marker='s')\n",
        "\n",
        "    ax.set_title('Real-time IoT Health Metrics')\n",
        "    ax.set_xlabel('Time')\n",
        "    ax.set_ylabel('Measurements')\n",
        "    ax.xaxis.set_major_formatter(DateFormatter('%H:%M'))\n",
        "    fig.autofmt_xdate()\n",
        "\n",
        "    ax.legend()\n",
        "    ax.grid(True)\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "\n",
        "\n",
        "def main():\n",
        "    parser = argparse.ArgumentParser(\n",
        "        description='Simulate diagnosis and IoT health monitoring.'\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        '-s', '--symptoms', nargs='+', default=['fever', 'cough', 'fatigue'],\n",
        "        help='List of patient symptoms.'\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        '-m', '--minutes', type=int, default=12,\n",
        "        help='Duration in minutes for IoT simulation.'\n",
        "    )\n",
        "    args = parser.parse_args()\n",
        "\n",
        "    logging.info(f\"Received symptoms: {args.symptoms}\")\n",
        "\n",
        "    results = diagnose(args.symptoms)\n",
        "    if results:\n",
        "        logging.info(\"Diagnosis results (most likely first):\")\n",
        "        for condition, score in results:\n",
        "            logging.info(f\"- {condition}: score {score}\")\n",
        "\n",
        "        top_condition = results[0][0]\n",
        "        treatment_steps = suggest_treatment(top_condition)\n",
        "        logging.info(f\"Suggested treatment for {top_condition}: {', '.join(treatment_steps)}\")\n",
        "    else:\n",
        "        logging.warning(\"No conditions matched the provided symptoms.\")\n",
        "\n",
        "    df = generate_iot_data(args.minutes)\n",
        "    logging.info(\"Sample IoT data:\\n%s\", df.head())\n",
        "    plot_vitals(df)\n",
        "\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    main()"
      ]
    }
  ]
}